app:
  salestax:
    - location: "CA"
      exempt: food
      rate: 0.0975
    - location: "NY"
      exempt: food,clothing
      rate: 0.08875
  productcat:
    "food": potato chips
    "clothing": shirt
